<h1 style="font-size:3rem;color:orange;">Machine Learning Quiz 1 

<h6 style="font-size:3rem;color:orange;">Abigail Dawn Davocol

# Part 1

# Creating 1D array for y and y_hat

In [221]:
import numpy as np
np.seterr(divide='ignore', invalid='ignore')

import math

y_hat = np.linspace(-1,1, num=20)
print(y_hat)

[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]


In [37]:
y = np.linspace(0,1,num=20)
print(y)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


# Computing dimension and shape for y_hat and y

<p>Shape and dimension of y_hat:</p>

In [26]:
print("Shape:",y_hat.shape)
print("Dimension:",y_hat.ndim)

Shape: (20,)
Dimension: 1


<p>Shape and dimension of y:</p>

In [32]:
print("Shape:",y.shape)
print("Dimension:",y.ndim)

Shape: (20,)
Dimension: 1


# Loss Functions

<p>Mean Squared Error:</p>

In [167]:
def mean_squared_error(actual, predicted):
    difference = np.subtract(actual,predicted)
    square = np.square(difference)
    return np.mean(square)

print(mean_squared_error(y,y_hat))

0.3421052631578948


<p>Mean Absolute Error:</p>

In [166]:
def mean_absolute_error(actual,predicted):
    difference = np.subtract(actual,predicted)
    absolute = np.absolute(difference)
    return(np.mean(absolute))
   
print(mean_absolute_error(y,y_hat))

0.4999999999999999


<p>Mean Squared Logarithmic Error:</p>

In [168]:
def mean_squared_log_error(actual, predicted,arrays_valid):
    
    if(arrays_valid):
        log_actual = np.log(actual)
        log_predicted = np.log(predicted)
    
        msle = np.square(np.subtract(log_actual,log_predicted))
        return (np.mean(msle))
    else:
        return "Array values contains negative values"

    
def check_if_array_is_valid(actual,predicted):
    if all(i > 0 for i in actual):
        actual_valid = True
    else:
        actual_valid = False
    if all(j > 0 for j in predicted): 
        predicted_valid = True
    else:
        predicted_valid = False
    
    return actual_valid or predicted_valid
       
print(mean_squared_log_error(y, y_hat, check_if_array_is_valid(y,y_hat)))

Array values contains negative values


<p>Mean Absolute Percentage Error:</p>

In [219]:
def mean_abs_percentage_error(actual, predicted):
    
    if all(i != 0 for i in actual):
        difference = np.subtract(actual,predicted)/actual
        mape = np.mean(np.abs(qoutient))*100
        print(np.abs(qoutient).mean())
        return mape
    else:
        return "y array contains a 0 value"

print(mean_abs_percentage_error(y,y_hat))

y array contains a 0 value


# Part 2

# Create a 1d array M{1,2,...16}

In [225]:
M = np.arange(start=1, stop=17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

# Reshape M into a 4x4 array

In [224]:
N = np.reshape(M,(4,4))
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# 2nd row of N

In [229]:
print(N[1])

[5 6 7 8]


# Minimum values for each column of N

In [238]:
#axis = 0 to get the columns of the matrix
min_values = np.min(N, axis=0) 

for i in range(len(min_values)):
    print ("Column " + str(i) + " minimum value:" + str(min_values[i]))

Column 0 minimum value:1
Column 1 minimum value:2
Column 2 minimum value:3
Column 3 minimum value:4


# Locations of the minimum values for each column of N

In [266]:
for i in range(len(min_values)):
    array_index = np.where(N==min_values[i]) 
    print ("Column " + str(i) + " minimum value " + str(min_values[i]) + " is located at index: " + str(array_index[1][0]))

Column 0 minimum value 1 is located at index: 0
Column 1 minimum value 2 is located at index: 1
Column 2 minimum value 3 is located at index: 2
Column 3 minimum value 4 is located at index: 3


# Get the average of the whole matrix

In [257]:
matrix_average = np.average(N)
print("Average of the whole matrix:", matrix_average)

Average of the whole matrix: 8.5


# vector V with 4 elements, each element is 1

In [261]:
listV = [1,1,1,1]

V = np.array(listV)
print("Vector with 4 elements:",V)

Vector with 4 elements: [1 1 1 1]


# Dot Product of N and V

In [265]:
dot_product = np.dot(N,V)
print("Dot product result:", dot_product)

Dot product result: [10 26 42 58]
